### ISSUE TITLE
Container runs out of memory during sync

### ISSUE THREAD

**Issue by tnet-ag** [dappnode/DAppNodePackage-erigon#135]
The 32GB Memory Limit of the Container in docker-compose.yml

```
    deploy:
      resources:
        limits:
          memory: 32768M
```

Produces a crash loop during early sync, cause the container runs out of memory

Increased the limit of the running container now manually to  64 GB with 

docker update --memory <new_memory_limit> <container_name>

and It works.

The limit should be increased in docker-compose.yml
